Aggregation
jtcramer/sonyc-kalman pull request #1
Opened 2019-11-06 15:34 UTC by tomxi

2019-11-06 18:59 UTC, jtcramer requested changes
Just the filename needs to be changed. Otherwise LGTM.

2019-11-06 18:59 UTC, jtcramer commented on sonyc_kalman/data.py
>      out_fname = "{}_{}minslot.npz".format(os.path.basename(args.hdf5_path).split('.')[0],
We should add the aggregation method in the filename

2019-11-07 18:03 UTC, ChrisIck commented
LGTM, no issues other than the naming conventions @jtcramer pointed out.

2019-11-14 19:39 UTC, jtcramer commented
LGTM

2019-11-14 19:39 UTC, jtcramer approved these changes

2019-11-14 19:39 UTC, merged