Pca implement
jtcramer/sonyc-kalman pull request #15
Opened 2019-11-21 15:18 UTC by ChrisIck

Demo notebook and training script that addresses and resolves #6

2019-11-28 00:36 UTC, jtcramer requested changes

2019-11-28 00:36 UTC, jtcramer commented on sonyc_kalman/train_pykalman.py
> +            model_name = sensor_name + '_pca.pkl'
I think this should be `pca_name`?

2019-11-28 00:36 UTC, jtcramer commented on sonyc_kalman/train_pykalman.py
> +    print('Training complete, saving result to {}'.format(os.path.join(params.output_path, model_name)))
This should probably go after `model_name` is defined below

2019-11-28 00:36 UTC, jtcramer commented on sonyc_kalman/train_pykalman.py
> +    print('Training complete, saving result to {}'.format(os.path.join(params.output_path, model_name)))
Also the whole path should be defined once rather than recomputing it everytime

2019-12-05 20:05 UTC, ChrisIck commented on sonyc_kalman/train_pykalman.py
> +            model_name = sensor_name + '_pca.pkl'
Fixed in latest push

2019-12-05 20:05 UTC, ChrisIck commented on sonyc_kalman/train_pykalman.py
> +    print('Training complete, saving result to {}'.format(os.path.join(params.output_path, model_name)))
Fixed in latest push

2019-12-05 20:06 UTC, merged